# Generated by Django 6.0.1 on 2026-01-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
